server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          products-client-client-credentials:
            provider: spring
            client-id: icceto
            client-secret: 123456
            authorization-grant-type: authorization_code
            client-name: products-client-client-credentials
            scope: openid
        provider:
          spring:
            issuer-uri: http://oauth-server:9000
